name: basic-actions
run-name: ${{ github.actor }} just pushed.
on: [push]
jobs:
  check_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: mirromutth/mysql-action@v1.1
        with:
          # The port of host
          host port: 3306
          # The port of container
          container port: 3306
          # --character-set-server - The character set of MySQL server
          character set server: # optional, default is utf8mb4
          # --collation-server - The character collation of MySQL server
          collation server: # optional, default is utf8mb4_general_ci
          # Version of MySQL to use
          mysql version: # optional, default is latest
          # MYSQL_ROOT_PASSWORD - root superuser password
          mysql root password: Barker123!
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: NutriLog
      - run: pip install -r ./requirements.txt
      - run: python3 ./RobertSUcks/createDB.py
                
